//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmbryoExpress.Res {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Instrument {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Instrument() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmbryoExpress.Res.Instrument", typeof(Instrument).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Calibrated 的本地化字符串。
        /// </summary>
        internal static string StrCalibrated {
            get {
                return ResourceManager.GetString("StrCalibrated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cleaned 的本地化字符串。
        /// </summary>
        internal static string StrCleaned {
            get {
                return ResourceManager.GetString("StrCleaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Degranulation  Cell Manipulation 的本地化字符串。
        /// </summary>
        internal static string StrDegranulation {
            get {
                return ResourceManager.GetString("StrDegranulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failure 的本地化字符串。
        /// </summary>
        internal static string StrFailure {
            get {
                return ResourceManager.GetString("StrFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frozen Embryo 的本地化字符串。
        /// </summary>
        internal static string StrFrozenEmbryo {
            get {
                return ResourceManager.GetString("StrFrozenEmbryo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High 的本地化字符串。
        /// </summary>
        internal static string StrHigh {
            get {
                return ResourceManager.GetString("StrHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Low 的本地化字符串。
        /// </summary>
        internal static string StrLow {
            get {
                return ResourceManager.GetString("StrLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maintained 的本地化字符串。
        /// </summary>
        internal static string StrMaintained {
            get {
                return ResourceManager.GetString("StrMaintained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal 的本地化字符串。
        /// </summary>
        internal static string StrNormal {
            get {
                return ResourceManager.GetString("StrNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Picking Egg 的本地化字符串。
        /// </summary>
        internal static string StrPickingEgg {
            get {
                return ResourceManager.GetString("StrPickingEgg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selection Embryo 的本地化字符串。
        /// </summary>
        internal static string StrSelectionEmbryo {
            get {
                return ResourceManager.GetString("StrSelectionEmbryo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        internal static string StrSuccess {
            get {
                return ResourceManager.GetString("StrSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thawed Embryo 的本地化字符串。
        /// </summary>
        internal static string StrThawedEmbryo {
            get {
                return ResourceManager.GetString("StrThawedEmbryo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transfer Embryo 的本地化字符串。
        /// </summary>
        internal static string StrTransferEmbryo {
            get {
                return ResourceManager.GetString("StrTransferEmbryo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnCalibrated 的本地化字符串。
        /// </summary>
        internal static string StrUncalibrated {
            get {
                return ResourceManager.GetString("StrUncalibrated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnClean 的本地化字符串。
        /// </summary>
        internal static string StrUnClean {
            get {
                return ResourceManager.GetString("StrUnClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnKnown 的本地化字符串。
        /// </summary>
        internal static string StrUnKnown {
            get {
                return ResourceManager.GetString("StrUnKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnMaintained 的本地化字符串。
        /// </summary>
        internal static string StrUnMaintained {
            get {
                return ResourceManager.GetString("StrUnMaintained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Urgent 的本地化字符串。
        /// </summary>
        internal static string StrUrgent {
            get {
                return ResourceManager.GetString("StrUrgent", resourceCulture);
            }
        }
    }
}
