//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmbryoExpress.Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class User {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal User() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmbryoExpress.Res.User", typeof(User).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username can only be characters(&quot;A to Z, a to z, _ or space&quot;) and/or numbers(&quot;0 to 9&quot;)..
        /// </summary>
        internal static string StrAddUser_Characters {
            get {
                return ResourceManager.GetString("StrAddUser_Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username already exists..
        /// </summary>
        internal static string StrAddUser_Exist {
            get {
                return ResourceManager.GetString("StrAddUser_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username should be between 1 to 32 characters..
        /// </summary>
        internal static string StrAddUser_NameTooLong {
            get {
                return ResourceManager.GetString("StrAddUser_NameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not match Confirm Password..
        /// </summary>
        internal static string StrAddUser_PasswordError {
            get {
                return ResourceManager.GetString("StrAddUser_PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of users has reached maximum 20. Cannot create new users..
        /// </summary>
        internal static string StrAddUser_TooMany {
            get {
                return ResourceManager.GetString("StrAddUser_TooMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username does not exist..
        /// </summary>
        internal static string StrDeleteUser_NotExist {
            get {
                return ResourceManager.GetString("StrDeleteUser_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete user {0}?.
        /// </summary>
        internal static string StrDeleteUser_SystemAsk {
            get {
                return ResourceManager.GetString("StrDeleteUser_SystemAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete system user..
        /// </summary>
        internal static string StrDeleteUser_SystemUser {
            get {
                return ResourceManager.GetString("StrDeleteUser_SystemUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete the user group {0}?.
        /// </summary>
        internal static string StrDeleteUserGroup_SystemAsk {
            get {
                return ResourceManager.GetString("StrDeleteUserGroup_SystemAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        ///Please check your username and password..
        /// </summary>
        internal static string StrLogin_Error {
            get {
                return ResourceManager.GetString("StrLogin_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong username. Login failed..
        /// </summary>
        internal static string StrLogin_UserError {
            get {
                return ResourceManager.GetString("StrLogin_UserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of system user password must be between 4 and 20 characters..
        /// </summary>
        internal static string StrModify_AdminPasswordLength {
            get {
                return ResourceManager.GetString("StrModify_AdminPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input New Password..
        /// </summary>
        internal static string StrModify_InputNewPassword {
            get {
                return ResourceManager.GetString("StrModify_InputNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password does not match Confirm Password..
        /// </summary>
        internal static string StrModify_NewPasswordNotMatch {
            get {
                return ResourceManager.GetString("StrModify_NewPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Old Password is incorrect..
        /// </summary>
        internal static string StrModify_PasswordError {
            get {
                return ResourceManager.GetString("StrModify_PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is too long. Should be between 0 to 20 characters..
        /// </summary>
        internal static string StrModify_PasswordTooLong {
            get {
                return ResourceManager.GetString("StrModify_PasswordTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming system user is not allowed..
        /// </summary>
        internal static string StrModify_SystemUser {
            get {
                return ResourceManager.GetString("StrModify_SystemUser", resourceCulture);
            }
        }
    }
}
