//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmbryoExpress.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmbryoExpress.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string AdminUser {
            get {
                return ResourceManager.GetString("AdminUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Central_Monitor {
            get {
                object obj = ResourceManager.GetObject("Central Monitor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string CommonUser {
            get {
                return ResourceManager.GetString("CommonUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Daily_Managerment {
            get {
                object obj = ResourceManager.GetObject("Daily Managerment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Diagnosis Report.
        /// </summary>
        internal static string ErrorDiagnosisReport {
            get {
                return ResourceManager.GetString("ErrorDiagnosisReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Export_Table {
            get {
                object obj = ResourceManager.GetObject("Export Table", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Information_Input {
            get {
                object obj = ResourceManager.GetObject("Information Input", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login {0}.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap problem_report {
            get {
                object obj = ResourceManager.GetObject("problem_report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This wizard will guide you through the Technical Support Request creation process.
        ///
        ///Technical Support Request creation wizard automatically collects the instrument configurations, NovoExpress system logs, current screenshot, current experiment file and other information that helps diagnosis and troubleshooting of the instrument. You can also attach any other files using this function..
        /// </summary>
        internal static string ProblemReportLabelCyte2ChineseEdition {
            get {
                return ResourceManager.GetString("ProblemReportLabelCyte2ChineseEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Quality_Control_Process {
            get {
                object obj = ResourceManager.GetObject("Quality Control Process", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Report_Managerment {
            get {
                object obj = ResourceManager.GetObject("Report Managerment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save_as_Picture {
            get {
                object obj = ResourceManager.GetObject("Save as Picture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SplashScreen2 {
            get {
                object obj = ResourceManager.GetObject("SplashScreen2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  has been added successfully..
        /// </summary>
        internal static string StrAddUserSuccess {
            get {
                return ResourceManager.GetString("StrAddUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign To.
        /// </summary>
        internal static string StrAssignTo {
            get {
                return ResourceManager.GetString("StrAssignTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built Date: .
        /// </summary>
        internal static string StrBuiltDate {
            get {
                return ResourceManager.GetString("StrBuiltDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading EmbryoExpress event logs, please wait..
        /// </summary>
        internal static string StrCollecting {
            get {
                return ResourceManager.GetString("StrCollecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Complete.
        /// </summary>
        internal static string StrComplete {
            get {
                return ResourceManager.GetString("StrComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} creation failed.
        /// </summary>
        internal static string strCreateFailedTitle {
            get {
                return ResourceManager.GetString("strCreateFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Report to create a Technical Support Request..
        /// </summary>
        internal static string StrCreateReport {
            get {
                return ResourceManager.GetString("StrCreateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create {0} failed. There is not enough disk space in the target location..
        /// </summary>
        internal static string strCreateReportFailed {
            get {
                return ResourceManager.GetString("strCreateReportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} creation is in progress, please wait..
        /// </summary>
        internal static string StrCreating {
            get {
                return ResourceManager.GetString("StrCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndTime.
        /// </summary>
        internal static string StrEndTime {
            get {
                return ResourceManager.GetString("StrEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input the username..
        /// </summary>
        internal static string StrInputUserName {
            get {
                return ResourceManager.GetString("StrInputUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string StrOK {
            get {
                return ResourceManager.GetString("StrOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OwnedBy.
        /// </summary>
        internal static string StrOwnedBy {
            get {
                return ResourceManager.GetString("StrOwnedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string StrPriority {
            get {
                return ResourceManager.GetString("StrPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} creation is complete, please click Next button to continue..
        /// </summary>
        internal static string StrProblemReportCreateFinish {
            get {
                return ResourceManager.GetString("StrProblemReportCreateFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string StrReport {
            get {
                return ResourceManager.GetString("StrReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string StrSubject {
            get {
                return ResourceManager.GetString("StrSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an unknown error. Please restart the program..
        /// </summary>
        internal static string StrUnknownErrorMsg {
            get {
                return ResourceManager.GetString("StrUnknownErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Support Request.
        /// </summary>
        internal static string TechnicalSupportRequest {
            get {
                return ResourceManager.GetString("TechnicalSupportRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap User_Management {
            get {
                object obj = ResourceManager.GetObject("User Management", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string WizardCreateButtonText {
            get {
                return ResourceManager.GetString("WizardCreateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;.
        /// </summary>
        internal static string WizardNextButtonText {
            get {
                return ResourceManager.GetString("WizardNextButtonText", resourceCulture);
            }
        }
    }
}
