//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmbryoExpress.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmbryoExpress.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Administrator 的本地化字符串。
        /// </summary>
        internal static string AdminUser {
            get {
                return ResourceManager.GetString("AdminUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Central_Monitor {
            get {
                object obj = ResourceManager.GetObject("Central Monitor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 User 的本地化字符串。
        /// </summary>
        internal static string CommonUser {
            get {
                return ResourceManager.GetString("CommonUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Daily_Managerment {
            get {
                object obj = ResourceManager.GetObject("Daily Managerment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Error Diagnosis Report 的本地化字符串。
        /// </summary>
        internal static string ErrorDiagnosisReport {
            get {
                return ResourceManager.GetString("ErrorDiagnosisReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Information_Input {
            get {
                object obj = ResourceManager.GetObject("Information Input", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Login {0} 的本地化字符串。
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap problem_report {
            get {
                object obj = ResourceManager.GetObject("problem_report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 This wizard will guide you through the Technical Support Request creation process.
        ///
        ///Technical Support Request creation wizard automatically collects the instrument configurations, NovoExpress system logs, current screenshot, current experiment file and other information that helps diagnosis and troubleshooting of the instrument. You can also attach any other files using this function. 的本地化字符串。
        /// </summary>
        internal static string ProblemReportLabelCyte2ChineseEdition {
            get {
                return ResourceManager.GetString("ProblemReportLabelCyte2ChineseEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Quality_Control_Process {
            get {
                object obj = ResourceManager.GetObject("Quality Control Process", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Report_Managerment {
            get {
                object obj = ResourceManager.GetObject("Report Managerment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap SplashScreen2 {
            get {
                object obj = ResourceManager.GetObject("SplashScreen2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似  has been added successfully. 的本地化字符串。
        /// </summary>
        internal static string StrAddUserSuccess {
            get {
                return ResourceManager.GetString("StrAddUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assign To 的本地化字符串。
        /// </summary>
        internal static string StrAssignTo {
            get {
                return ResourceManager.GetString("StrAssignTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Built Date:  的本地化字符串。
        /// </summary>
        internal static string StrBuiltDate {
            get {
                return ResourceManager.GetString("StrBuiltDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reading EmbryoExpress event logs, please wait. 的本地化字符串。
        /// </summary>
        internal static string StrCollecting {
            get {
                return ResourceManager.GetString("StrCollecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 % Complete 的本地化字符串。
        /// </summary>
        internal static string StrComplete {
            get {
                return ResourceManager.GetString("StrComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} creation failed 的本地化字符串。
        /// </summary>
        internal static string strCreateFailedTitle {
            get {
                return ResourceManager.GetString("strCreateFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click Report to create a Technical Support Request. 的本地化字符串。
        /// </summary>
        internal static string StrCreateReport {
            get {
                return ResourceManager.GetString("StrCreateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create {0} failed. There is not enough disk space in the target location. 的本地化字符串。
        /// </summary>
        internal static string strCreateReportFailed {
            get {
                return ResourceManager.GetString("strCreateReportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} creation is in progress, please wait. 的本地化字符串。
        /// </summary>
        internal static string StrCreating {
            get {
                return ResourceManager.GetString("StrCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EndTime 的本地化字符串。
        /// </summary>
        internal static string StrEndTime {
            get {
                return ResourceManager.GetString("StrEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input the username. 的本地化字符串。
        /// </summary>
        internal static string StrInputUserName {
            get {
                return ResourceManager.GetString("StrInputUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string StrOK {
            get {
                return ResourceManager.GetString("StrOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OwnedBy 的本地化字符串。
        /// </summary>
        internal static string StrOwnedBy {
            get {
                return ResourceManager.GetString("StrOwnedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Priority 的本地化字符串。
        /// </summary>
        internal static string StrPriority {
            get {
                return ResourceManager.GetString("StrPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} creation is complete, please click Next button to continue. 的本地化字符串。
        /// </summary>
        internal static string StrProblemReportCreateFinish {
            get {
                return ResourceManager.GetString("StrProblemReportCreateFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Report 的本地化字符串。
        /// </summary>
        internal static string StrReport {
            get {
                return ResourceManager.GetString("StrReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subject 的本地化字符串。
        /// </summary>
        internal static string StrSubject {
            get {
                return ResourceManager.GetString("StrSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encountered an unknown error. Please restart the program. 的本地化字符串。
        /// </summary>
        internal static string StrUnknownErrorMsg {
            get {
                return ResourceManager.GetString("StrUnknownErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Technical Support Request 的本地化字符串。
        /// </summary>
        internal static string TechnicalSupportRequest {
            get {
                return ResourceManager.GetString("TechnicalSupportRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap User_Management {
            get {
                object obj = ResourceManager.GetObject("User Management", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Create 的本地化字符串。
        /// </summary>
        internal static string WizardCreateButtonText {
            get {
                return ResourceManager.GetString("WizardCreateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next &gt; 的本地化字符串。
        /// </summary>
        internal static string WizardNextButtonText {
            get {
                return ResourceManager.GetString("WizardNextButtonText", resourceCulture);
            }
        }
    }
}
